Feature/sonya
CS342/CS342-2023-Application pull request #21
Opened 2023-01-24 05:38 UTC by sonyashijin

# *Name of the PR*

## :recycle: Current situation & Problem
Not added to class app

## :bulb: Proposed solution
*Describe the solution and how this affects the project and internal structure*

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
*Are there tests included? If yes, which situations are tested, and which corner cases are missing?*

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

2023-01-27 23:20 UTC, PSchmiedmayer requested changes
Hi @sonyashijin,

Thank you for your PR and for adding some information about you to the CS342 class application!

One of the tasks of Assignment 1 is a creative and nice addition beyond the views that we have in the application.
Feel free to add a more creative solution for the second round of review if you want to.

I have added some comments to your current state of the PR on improving your code and adhering to the REUSE specification.

I have also merged the latest main state in your branch to make merging the PR easy so you can see the current checks that are failing. You will have to at least solve one merge conflict before you merge the PR, as there will likely be some additional commits to the main branch until then.
Be sure that you `git pull` the latest state to your local version if you accept any of the suggestions here on GitHub and get the merge conflict to your local branch 👍

2023-01-27 23:20 UTC, PSchmiedmayer commented on CS342MemberViews/Sources/SonyaJin/ProfileView.swift
> +            .aspectRatio(1.0, contentMode: .fit)
You can add the `scaledToFill()` modifier to fix the squeezing of your image:
```suggestion
            .resizable()
            .scaledToFill()
            .aspectRatio(1.0, contentMode: .fit)
```

2023-01-27 23:20 UTC, PSchmiedmayer commented on CS342MemberViews/Sources/SonyaJin/ProfileView.swift
> +        guard let imagePath = Bundle.module.path(forResource: "SonyaJin", ofType: "jpeg"),
Your image is not displayed in the view. This is due to the fact that you have added the wrong path extension:
```suggestion
        guard let imagePath = Bundle.module.path(forResource: "SonyaJin", ofType: "jpg"),
```

2023-01-27 23:20 UTC, PSchmiedmayer commented on CS342MemberViews/Sources/SonyaJin/Resources/SonyaJinBio.md
> +
You Bio does not include any information.

2023-01-27 23:20 UTC, PSchmiedmayer commented on CS342MemberViews/Package.swift
> +            ],
You get an error message that you having an invalid `exclude` statement. 
You are trying to exclude the _"Resources/SonyaJin.jpeg.license"_ and _"Resources/SonyaJin.md.license"_ files but you have not added any of these files to the repo. Please add these files including a proper license so your REUSE checks are passing. You can find out more about the REUSE and SwiftLint checks here: https://reuse.software/spec/ . Please refer to the other Swift Package targets and files to see the typical license header that we are using.

2023-01-27 23:25 UTC, PSchmiedmayer commented on CS342MemberViews/Sources/SonyaJin/ProfileView.swift
> +        guard let imagePath = Bundle.module.path(forResource: "SonyaJin", ofType: "jpeg"),
@sonyashijin I have committed a fix to your issue here to get you started with adding some more creative views.

2023-01-27 23:25 UTC, PSchmiedmayer commented on CS342MemberViews/Sources/SonyaJin/ProfileView.swift
> +            .aspectRatio(1.0, contentMode: .fit)
@sonyashijin I have committed a fix to your issue here to get you started with adding some more creative views.

2023-02-01 01:24 UTC, vishnuravi commented
@PSchmiedmayer Sonja and I met and worked on these revisions together. Please re-review and let her know if you have any other comments!

2023-02-01 01:37 UTC, PSchmiedmayer approved these changes

2023-02-01 01:45 UTC, merged

2023-02-01 01:50 UTC, PSchmiedmayer commented
@sonyashijin Thank you for your changes. All tests passed and I merged your changes 🚀

2023-02-02 22:41 UTC, sonyashijin commented
@PSchmiedmayer @vishnuravi Thank you for reviewing and for your help!